title: mfa.tax
description: >-
  A list of vendors that treat Multi-Factor Authentication (MFA)
  as a luxury feature, not a core security requirement.

url: https://mfa.tax

theme: jekyll-theme-cayman
kramdown:
  parse_block_html: true
